//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UndertaleBattleSystemPrototype.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UndertaleBattleSystemPrototype.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap actButton {
            get {
                object obj = ResourceManager.GetObject("actButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap actButtonBlank {
            get {
                object obj = ResourceManager.GetObject("actButtonBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fightButton {
            get {
                object obj = ResourceManager.GetObject("fightButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fightButtonBlank {
            get {
                object obj = ResourceManager.GetObject("fightButtonBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heart {
            get {
                object obj = ResourceManager.GetObject("heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap itemButton {
            get {
                object obj = ResourceManager.GetObject("itemButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap itemButtonBlank {
            get {
                object obj = ResourceManager.GetObject("itemButtonBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mercyButton {
            get {
                object obj = ResourceManager.GetObject("mercyButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mercyButtonBlank {
            get {
                object obj = ResourceManager.GetObject("mercyButtonBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Player&gt;
        ///  &lt;Stats&gt;
        ///    &lt;General Name =&quot;Chris&quot;
        ///             Lvl =&quot;1&quot;
        ///             gold =&quot;0&quot;
        ///             exp =&quot;0&quot;&gt;
        ///    &lt;/General&gt;
        ///    &lt;Battle currentHP =&quot;20&quot;
        ///            maxHP =&quot;20&quot;
        ///            atk =&quot;0&quot;
        ///            def =&quot;0&quot;&gt;
        ///    &lt;/Battle&gt;
        ///  &lt;/Stats&gt;
        ///  &lt;Items&gt;
        ///    &lt;Equiped weapon =&quot; &quot;
        ///             armor =&quot; &quot;&gt;
        ///    &lt;/Equiped&gt;
        ///    &lt;Inventory item1 =&quot; &quot;
        ///               item2 =&quot; &quot;
        ///               item3 =&quot; &quot;
        ///               item4 =&quot; &quot;&gt;
        ///    &lt;/Inventory&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Enemy&gt;
        ///  &lt;Stats&gt;
        ///    &lt;Attack&gt;2&lt;/Attack&gt;
        ///    &lt;Defence&gt;0&lt;/Defence&gt;
        ///  &lt;/Stats&gt;
        ///  &lt;ActMenu&gt;
        ///    &lt;Act actName =&quot;Check&quot; 
        ///          actLine1 =&quot;TESTENEMY 2 ATK 0 DEF&quot;
        ///          actLine2 =&quot;Basic enemy example&quot;&gt; 
        ///    &lt;/Act&gt;
        ///    &lt;Act actName =&quot;Joke&quot;
        ///          actLine1 =&quot;Test Enemy laughs.&quot;
        ///          actLine2 =&quot;...&quot;
        ///          actLine3 =&quot;It&apos;s fake laughter though.&quot;&gt;
        ///    &lt;/Act&gt;
        ///    &lt;Act actName =&quot;Taunt&quot;
        ///          actLine1 =&quot;Test Enemy just stares at you.&quot;&gt;
        ///    &lt;/A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestEnemy {
            get {
                return ResourceManager.GetString("TestEnemy", resourceCulture);
            }
        }
    }
}
